name: furpals
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_messaging: ^16.1.3
  image_picker: ^1.2.1
  firebase_storage: ^13.2.0
  video_player: ^2.11.1
  video_compress: ^3.1.2
  gal: ^2.0.3
  image_cropper: ^12.1.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# App Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#F9C8D0"
  adaptive_icon_foreground: "assets/images/logo.png"
  background_color: "#F9C8D0"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#F9C8D0"
    theme_color: "#F9C8D0"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/cat_icon.png
    - assets/images/dog_icon.png
    - assets/images/home_b.png
    - assets/images/plus_button.png
    - assets/images/user.png
    - assets/images/loc_button.png
    - assets/images/logo.png
    - assets/images/fb_icon.png
    - assets/images/google_icon.png

  fonts:
    - family: Modak
      fonts:
        - asset: fonts/Modak-Regular.ttf