// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQUAXzZnIQlv9TcmTbXLL-EXJjUu_-G4',
    appId: '1:933596402950:web:ec93285494845627ebfa87',
    messagingSenderId: '933596402950',
    projectId: 'furpals-13a2f',
    authDomain: 'furpals-13a2f.firebaseapp.com',
    storageBucket: 'furpals-13a2f.firebasestorage.app',
    measurementId: 'G-1ZSBXEMTSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoup9KiHqgk0QZI6j_40QBmORw78-j010',
    appId: '1:933596402950:android:26c69f9192c2c8f7ebfa87',
    messagingSenderId: '933596402950',
    projectId: 'furpals-13a2f',
    storageBucket: 'furpals-13a2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvYZlgcIXDo1VxGCM3osntU5WRyCKILc',
    appId: '1:933596402950:ios:8bcbbf17c9272f8aebfa87',
    messagingSenderId: '933596402950',
    projectId: 'furpals-13a2f',
    storageBucket: 'furpals-13a2f.firebasestorage.app',
    iosClientId: '933596402950-2k19oiqdisblpsagqncs2jeas53v3fde.apps.googleusercontent.com',
    iosBundleId: 'com.example.furpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvYZlgcIXDo1VxGCM3osntU5WRyCKILc',
    appId: '1:933596402950:ios:8bcbbf17c9272f8aebfa87',
    messagingSenderId: '933596402950',
    projectId: 'furpals-13a2f',
    storageBucket: 'furpals-13a2f.firebasestorage.app',
    iosClientId: '933596402950-2k19oiqdisblpsagqncs2jeas53v3fde.apps.googleusercontent.com',
    iosBundleId: 'com.example.furpals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNQUAXzZnIQlv9TcmTbXLL-EXJjUu_-G4',
    appId: '1:933596402950:web:9babaeea8a652bacebfa87',
    messagingSenderId: '933596402950',
    projectId: 'furpals-13a2f',
    authDomain: 'furpals-13a2f.firebaseapp.com',
    storageBucket: 'furpals-13a2f.firebasestorage.app',
    measurementId: 'G-9LTYEQ4J99',
  );

}